### ISSUE TITLE
Error reading in MeanSize_at_Age_obs data with sample_struct

### ISSUE THREAD

**Issue by skylersagarese-NOAA** [nmfs-fish-tools/SSMSE#170]
My initial data read was not successful using sample_struct because of an issue reading in the MeanSize_at_Age_obs. I get the following error:

Error in unique(as.numeric(tmp_n)) : 
'list' object cannot be coerced to type 'double'

The error goes away when I set my MeanSize_at_Age_obs in my data file to NA.

**Comment by k-doering-NOAA** [comment]
Thanks for reporting @skylersagarese-NOAA,  I think the error is coming from this line of code:

https://github.com/nmfs-fish-tools/SSMSE/blob/d1e7714a61e4925b377f0930d654a6a74202a5e6/R/sample_struct.R#L295

Do you know which version of r4ss you are using? I'm wondering if that could affect it.

**Comment by skylersagarese-NOAA** [comment]
I'm currently using r4ss version 1.48.1

**Comment by k-doering-NOAA** [comment]
Thanks - I won't be able to take a look until tomorrow, but if you have an example data file and code you could send my way (either on this thread or via email or google drive), that would be really helpful!

**Comment by k-doering-NOAA** [comment]
I think the issue was the object was a data frame, so it needed to be unlisted before `as.numeric()` could be used.

I pushed the changed to https://github.com/nmfs-fish-tools/SSMSE/tree/fix-meansizeatage for now, so @skylersagarese-NOAA, if you are able to test, you can install ssmse using

```r
remotes::install_github("nmfs-fish-tools/SSMSE@fix-meansizeatage")
```

then try using 
`SSMSE::create_sample_struct()` again with your data file.

Also, another note: I found a note in the code that says the sample size cannot be set for each bin and sex like it can in SS3, so the sampling functionality for mean body size at age is very limited (and maybe not useful, thinking more about it).

https://github.com/nmfs-fish-tools/SSMSE/blob/d1e7714a61e4925b377f0930d654a6a74202a5e6/R/sample_struct.R#L23-L25

**Comment by skylersagarese-NOAA** [comment]
Thanks Kathryn, this fixed the reading in issue!

**Comment by k-doering-NOAA** [comment]
Thanks for confirming! The change has been pushed to the main branch.
