### ISSUE TITLE
Set seed for SS model runs (to make README example reproducible)

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-fish-tools/SSMSE#27]
I tried the example in the README and I was able to run SSMSE and produce the OM but the EM trajectories look different than the saved figure (see below). I am not sure if this is a known behaviour or not so I thought it would be better to report it rather than assume. I am guessing that setting the seed only sets the OM and that the EM is subject to convergence issues, though we might want to investigate the provided EM a bit more to have a more stable model.

![image](https://user-images.githubusercontent.com/4108564/86479883-cff86180-bd01-11ea-8f72-91719c4079ed.png)

**Comment by k-doering-NOAA** [comment]
Thanks @kellijohnson-NOAA ! I know @nathanvaughan-NOAA recently added in a function to create seeds for each scenario or iteration, but I don't think they are getting passed to the SS models yet (not yet setting the seed in the starter file). Is this accurate, Nathan? I agree it would be good to work on getting a reproducible example up and running, though (and would help us "check" that setting the seeds works as expected).

Kelli, do you have any thoughts about best practices for using seeds? In the past, I've always just set a single seed for an analysis at the top of an R script or passed a single value to a model, but I've never dealt with using them in simulation studies (when you have many model runs happening). Nathan has developed [a function to give users some different options with setting the seeds](https://github.com/nmfs-fish-tools/SSMSE/blob/master/R/utils.R#L744), but I wonder if users need more or less flexibility? (Nathan, feel free to chime in with thoughts about seeds, too - I think you've spent more time thinking about this than I have.)

**Comment by kellijohnson-NOAA** [comment]
In ss3sim, we have a matrix of recruitment deviations that are generated behind the scenes that have a set seed. Users can use those deviations by doing nothing or pass in their own deviations. Things get complicated when you allow stuff to run in parallel. For instance, is the seed set the same in every instance. Also, if the seed isn't reset for each random process sampling won't be the same anyway. For example if you sample 10 ages one time then 15 the next time, then the lengths that come after won't be the same. We didn't worry about this and only worried about recruitment deviations given that they are the main driving force.

**Comment by nathanvaughan-NOAA** [comment]
Kathryn is correct, I have only set up creating the seeds and using them
for some R based functionality such as creating recruitment deviation
sequences. I haven't implemented pushing them to SS. I'm also uncertain
about the best approach to setting the seeds. I think that having the user
input a single seed will be best in 99% of cases. I have it set up
currently to produce scenario and iteration specific seeds so that the
number of iterations in a scenario for instance, or the simulation length
doesn't mess up the seeding of all later scenarios. It is possible in my
set up for users to directly specify both scenario and iteration specific
seeds. I think that this could be useful for replicating bugs or wild
iteration outcomes that users want to investigate or merging separate MSE
scenarios and retaining the same scenario seeds.

**Comment by nathanvaughan-NOAA** [comment]
Thanks Kelli, those kind of roll on issues are what I was trying to avoid.
I have had them before as well with parallel processing simulations. What I
have done is say the user gives a global seed, the code then sets up a base
seed for each scenario, starting from that global seed. Then it creates a
base seed for every iteration within a scenario starting from the scenario
specific base seed. Then when seeds are used to produce something such as
rec devs the iteration base seed is used with a fixed offset such as
set.seed(seed=(base.seed+99)) a unique fixed offset is then hard coded in
whenever we have random numbers being generated such as rec devs or
implementation errors. The seeds are therefore constantly being reset
preventing any rollover error or contamination across parallel processing
runs. This should make anything in R reproducible but we probably don't
have that kind of control within SS such that any change to the specified
sampling within an SS run will have rollon impacts to all it's results.

**Comment by kellijohnson-NOAA** [comment]
You can set the seed in SS now.

**Comment by k-doering-NOAA** [comment]
@nathanvaughan-NOAA the ability to set the seed in SS is really new ( I think as of 3.30.15), so that's probably why you weren't aware of it. The set up is shown in page 22 of the [SS 3.30.15 user manual](https://doi.org/10.25923/5wpn-qt71).

Thanks @kellijohnson-NOAA for describing what ss3sim does and why. It makes sense that setting seeds for recdevs is most important. 

Nathan, I think your approach makes sense to make sure each process has the seed set before starting and should work well as long as the user is able to trace back what the seed was.  If we want to fix the seed in SS runs (which I think we should), maybe we need to expand a bit on your current scheme? For ex, do we need to have a new seed for each run of OM bootstrapping feature or the EM in the MSE loop (I think yes??) and could we derive this from the iteration seed with the run_SSMSE_iter function (or other lower level functions), maybe using your fixed offset seed approach? Or maybe the seeds for each SS run should be determined in the set_SSMSE_seeds function  (although you would need to pass more inputs to determine the number of seeds needed)?

**Comment by k-doering-NOAA** [comment]
I just tested and got identical EM model data files when running the same code twice - so I think the seed is being set properly now (it is being set in the SS starter files now). maybe @nathanvaughan-NOAA or @kellijohnson-NOAA could see if they get the same results when re-running the readme code (from README.rmd), if either of you have time to run it? Note that the results have changed since this issue opened, likely as a result of bug fixes.

**Comment by kellijohnson-NOAA** [comment]
I got plots that look the same as what is posted currently on the readme. Is that what I should be comparing it to?

**Comment by k-doering-NOAA** [comment]
That seems like a fine comparison, thank you!
