### ISSUE TITLE
SSMSE not compatible with F method 1

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-fish-tools/SSMSE#50]
Tested out a 2017 yellowtail rock fish model that uses F method 1; had issues because the TIME_SERIES table in report.sso includes Hrate instead of F when F method = 1. The F values from this table are used in the `get_F()` function, which is called when extending the OM and several other places.

F method 1 is not commonly used anymore from what I understand (using F method 3 instead is recommended), so I'm not sure whether it is worth the effort to try to fix this, or if it would be better to just exit on error if the OM or EM uses F method 1?

**Comment by iantaylor-NOAA** [comment]
I have no recollection of why we used F Method  1=Pope instead of 3=hybrid for the Yellowtail Rockfish model. Neither "Pope" nor "hybrid" occur in the assessment report. 

I agree that option 1 is relatively uncommon now and I think you could exit with an error and put off supporting option 1 unless you hear from from interested users that their models use this option and they don't want to change (the two options may provide very similar model results anyway).

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA,  it is helpful to have someone fact check my assumptions, like that F method 1 isn't used that often.

 I noticed some of the other SS testing models use method 1 also, but I assumed they were older models? I think supporting F method 1 would be really easy if SSMSE were refactored to not use any forecasting in the OM (on the to-do list, but not the highest priority right now), so I think the simpler exit on error solution works in the meantime.
