### ISSUE TITLE
Using a custom OM creates an infinite folder recursion

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [nmfs-fish-tools/SSMSE#74]
I'm trying to use SSMSE on a new OM based on the 2019 petrale sole assessment. If I run the below code, I think the OM files are created correctly but it never ends and just continues to create nested folders forever.
```

petrale_mod_path <- here("om")
run_SSMSE_dir <- file.path("run_SSMSE-ex")
dir.create(run_SSMSE_dir)

develop_OMs(OM_in_dir = petrale_mod_path, out_dir = run_SSMSE_dir, par_name = "L_at_Amax_Fem_GP_1",
            par_vals = 80, refit_OMs = FALSE, hess = FALSE)
```

`petrale_mod_path` is an OM directory I've created, and running this code creates a folder structure like "om"-> "run_SSMSE-ex" -> "om_L_at_A_max" -> "run_SSMSE-ex" -> "om" -> ... ad infinitum

Please let me know if this is a bug or if I'm doing something wrong!

**Comment by k-doering-NOAA** [comment]
Thanks for reporting, Christine, I will check this out tomorrow!

**Comment by ChristineStawitz-NOAA** [comment]
Update - I just realized maybe "om" was a name used by SSMSE so I tried 

`petrale_mod_path <- here("om_SSMSE")`

and now it exits but gives the following warning: 

`
Warning message:
In file.rename(from = file.path(out_dir, basename(OM_in_dir)), to = tmp_mod_path) :
  cannot rename file 'run_SSMSE-ex/om_SSMSE' to 'run_SSMSE-ex/om_SSMSE_L_at_Amax_Fem_GP_1_80', reason 'Access is denied'`

**Comment by ChristineStawitz-NOAA** [comment]
Oh I just stumbled upon this while debugging in the `run_SSMSE_iter` function 

```
#' @param OM_name Name of a valid Stock Synthesis stock assessment model from
#'   which to create the OM. Currently, only allows models in the package, so
#'   valid inputs are: \code{"cod"}.
```

If only package models are allowed, it would make sense why petrale isn't working!

**Comment by k-doering-NOAA** [comment]
Sorry, looks like that documentation is outdated! It is possible to use models not in the package (although I think wt at age ones may not work, we haven't tested them). I'll correct that. Feel free to report any other questionable docs you see  (or edit them yourself, if feeling up to it!)

When I try this code, it works:
```
library(SSMSE)
petrale_mod_path <- file.path("om") # I changed this from here pkg to be clear where the model files were relative to my wd
run_SSMSE_dir <- file.path("run_SSMSE-ex")
dir.create(run_SSMSE_dir)

develop_OMs(OM_in_dir = petrale_mod_path, out_dir = run_SSMSE_dir, par_name = "L_at_Amax_Fem_GP_1",
            par_vals = 80, refit_OMs = FALSE, hess = FALSE)
```

However, I do get errors if I try the function but get an error (e.g., there is no control.ss_new file), and then I try to run again without deleting the files in run_SSMSE_dir. Could that be what was going on the second time? 

Also, maybe the petrale_mod_path was different from what I tried, which is why I didn't the infinite folder loop?

**Comment by k-doering-NOAA** [comment]
@ChristineStawitz-NOAA, let me know if there was anything else on this issue that needs fixing! I am closing, but please feel free to reopen.
