### ISSUE TITLE
Error message references that only cod model can be used

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [nmfs-fish-tools/SSMSE#76]
I found another instance where the message says only the inbuilt cod model can be used although @k-doering-NOAA says it now should work with multiple models:

running `develop_OMs`

```
Error in develop_OMs(OM_name = "growth_timevary", out_dir = run_SSMSE_dir,  : 
  OM_name growth_timevary matched 0 models in SSMSE external package data, but should match 1. Please change OM_name to match (or partially match unambiguously) with 1 model in the models folder of the SSMSE external package data. Model options are: cod
```

**Comment by k-doering-NOAA** [comment]
Thanks @ChristineStawitz-NOAA! I think the issue was because the "growth_timevary" model was specified in `OM_name`, rather than the `OM_in_dir`.  Could you try changing it and seeing if it works?

Also, this issue made me realize that `OM_name` and `OM_in_dir` were not working in this function the same as in run_SSMSE, so I was able to push some changes - thanks so much!  You can get them by reinstalling SSMSE's main branch

**Comment by k-doering-NOAA** [comment]
thanks @ChristineStawitz-NOAA which made me realize that the growth_timevary and SR_env_block models were also included as prebuilt options. The documentation should mention these as well (and perhaps also list some features).
